---
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: restart pulseaudio service
  systemd:
    name: "pulseaudio.service"
    state: restarted
- name: run systemd-sysusers
  command: |
    /usr/bin/systemd-sysusers
- name: run systemd-tmpfiles
  command: |
    /usr/bin/systemd-tmpfiles --create
- name: reload udev
  shell: |
    udevadm control --reload-rules
    udevadm trigger
- name: restart iptables service
  systemd:
    name: "iptables.service"
    state: restarted
