---
# FIXME We should not do that through pip but through yay instead
- name: install pip
  yay:
    name: "python-pip"
    state: present
- name: install deepmerge
  pip:
    name: "deepmerge"
    state: present

- name: build and install
  include_role:
    name: "arch-package"
  vars:
    arch_package_name: "telegram-interaction"

- name: configure
  include: "./configure.yml"
