---
- name: install packages
  yay:
    name: "{{ item }}"
    state: present
  loop:
  - pulseaudio
  - pulseaudio-zeroconf
- name: copy service file for systemd
  copy:
    content: |
      [Unit]
      Description=PulseAudio system server

      [Service]
      ExecStart=/usr/bin/pulseaudio --realtime --no-cpu-limit --system --disallow-exit
      ExecReload=/bin/kill -HUP $MAINPID

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/pulseaudio.service"
  notify: reload systemd
- name: start service
  systemd:
    name: "pulseaudio.service"
    state: started
    enabled: yes
- name: fix systemd-sysusers missing folder
  file:
    path: "/etc/sysusers.d"
    state: directory
- block:
  #- copy:
  #    content: |
  #      SUBSYSTEM=="sound", ATTR{id}=="OdroidXU4", ENV{PULSE_IGNORE}="1"
  #    dest: "/etc/udev/rules.d/72-pulseaudio.rules"
  #  notify:
  #  - reload udev
  #  - restart pulseaudio service
  - name: add modules
    lineinfile:
      dest: "/etc/pulse/system.pa"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
    - { regexp: "(# *)?load-module module-zeroconf-publish", line: "load-module module-zeroconf-publish" }
    - { regexp: "(# *)?load-module module-native-protocol-tcp", line: "load-module module-native-protocol-tcp auth-anonymous=1" }
    notify: restart pulseaudio service
  - name: set card profiles
    lineinfile:
      regexp: "(# *)?set-card-profile {{ item.name }}"
      line: "set-card-profile {{ item.name }} {{ item.profile }}"
      dest: "/etc/pulse/system.pa"
    when: item.profile
    loop: "{{ pulseaudio_cards }}"
    notify: restart pulseaudio service
  - name: set sink descriptions
    lineinfile:
      regexp: "(# *)?update-sink-proplist {{ item.name }}"
      line: "update-sink-proplist {{ item.name }} device.description={{ item.description }}"
      dest: "/etc/pulse/system.pa"
    when: item.description
    loop: "{{ pulseaudio_sinks }}"
    notify: restart pulseaudio service
  - name: add tmpfiles for systemd
    copy:
      content: |
        u pulse - - /var/cache/pulse
        g pulse-access - -
      dest: "/etc/sysusers.d/pulseaudio.conf"
    notify: run systemd-sysusers
  - name: add sysusers for systemd
    copy:
      content: |
        d /var/cache/pulse 0755 pulse pulse -
      dest: "/etc/tmpfiles.d/pulseaudio.conf"
    notify: run systemd-tmpfiles
  - name: add iptables rule
    copy:
      content: |
        -A INPUT -i {{ pulseaudio_iface_name }} -p tcp --dport {{ pulseaudio_port }} -j ACCEPT
      dest: "/etc/iptables/iptables.rules.d/10-pulseaudio.rules"
    notify: restart iptables service
