---
- hosts: kimsufi-01
  gather_facts: no
  become: yes
  roles:
  #- include_role:
  #    name: "encheres-publiques"
  #  tags:
  #  - "encheres-publiques"
  #- include_role:
  #    name: "telegram-interaction"
  #  tags:
  #  - "interaction"
  - role: "telegram-interaction"
    tags:
    - "interaction"
  - role: "scraping"
    tags:
    - "scraping"
  - role: "maintenance"
    vars:
      maintenance_vault_password: "{{ lookup('file', '../.vault-password') }}"
      maintenance_ssh_config: "{{ lookup('file', '../../ssh/config') }}"
      #maintenance_ssh_private_key: "{{ lookup('file', '../.vault-password') }}"
      #maintenance_ssh_public_key: "{{ lookup('file', '../.vault-password') }}"
    tags:
    - "maintenance"

#- hosts: odroid-01
#  gather_facts: no
#  become: yes
#  roles:
#  - role: "pulseaudio"
#    tags:
#    - "pulseaudio"
