---
- hosts: kimsufi-01
  gather_facts: no
  become: yes
  tasks:
  - include_role:
      name: "encheres-publiques"
    tags:
    - "encheres-publiques"
  - include_role:
      name: "telegram-interaction"
    tags:
    - "interaction"

- hosts: odroid-01
  gather_facts: no
  become: yes
  roles:
  - role: "pulseaudio"
    tags:
    - "pulseaudio"
