---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - include: "provision/maintenance.yml"
    tags:
    - "maintenance"
  - include: "provision/hardening.yml"
    tags:
    - "hardening"
  - include: "provision/private-network.yml"
    tags:
    - "private-network"
