---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - include: "provision/maintenance.yml"
    tags:
    - "maintenance"
  - include: "provision/hardening.yml"
    tags:
    - "hardening"
  - include: "provision/private-network.yml"
    tags:
    - "private-network"

- hosts: storage-server
  gather_facts: no
  become: yes
  tasks:
  - include: "provision/storage-server.yml"
    tags:
    - "storage"

- hosts: storage-client
  gather_facts: no
  become: yes
  tasks:
  - include: "provision/storage-client.yml"
    tags:
    - "storage"

- hosts: scanner-server
  gather_facts: no
  become: yes
  roles:
  - role: "scanner"
    vars:
      scanner_mode: "server"
    tags:
    - "scanner"
