---
- name: create /etc/sysusers.d folder
  file:
    path: "/etc/sysusers.d"
    state: directory

- name: setup user for systemd
  copy:
    content: |
      u "{{ storage_client_user }}" {{ storage_client_uid }} "Storage User"
      g "{{ storage_client_user }}" {{ storage_client_uid }}
    dest: "/etc/sysusers.d/storage.conf"
  register: setup_user_for_systemd

- name: create user with systemd
  command: |
    systemd-sysusers
  when: setup_user_for_systemd.changed

- name: create STORAGE folder
  file:
    path: "/mnt/STORAGE"
    state: directory

- name: load nfs module
  copy:
    content: |
      nfs
    dest: "/etc/modules-load.d/nfs.conf"
  notify:
  - restart systemd-modules-load service

- name: create disk mount for systemd
  copy:
    content: |
      [Unit]
      Description=Data Mount

      [Mount]
      What=storage.local:/srv/nfs4/DATA
      Where=/mnt/DATA
      Type=nfs
      Options=user,soft
      TimeoutSec=10s

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/mnt-DATA.mount"
  notify: reload systemd daemon

- name: create disk autoumount for systemd
  copy:
    content: |
      [Unit]
      Description=Data Automount Point

      [Automount]
      Where=/mnt/DATA
      TimeoutIdleSec=1min

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/mnt-DATA.automount"
  notify: reload systemd daemon

- name: start systemd automount for disks
  systemd:
    name: "mnt-DATA.automount"
    state: started
    enabled: yes
