- include_role:
    name: "fail2ban"
- name: copy whistleblower action file for fail2ban
  copy:
    content: |
      [Definition]
      actionban = whistleblowerctl send-message --text="L'IP <ip> a été bannie à cause de <name>. "
      actionunban = whistleblowerctl send-message --text="L'IP <ip> a été graciée. "
    dest: "/etc/fail2ban/action.d/whistleblower.conf"
  notify:
  - restart fail2ban service

- include_role:
    name: "knockd"

- include_role:
    name: "iptables"

- include_role:
    name: "ssh-server"
# FIXME: Normalize like fail2ban & co.
- name: copy script file for whistleblower
  copy:
    content: |
      #!/bin/sh

      # See: http://sandrinodimattia.net/posting-successful-ssh-logins-to-slack/

      if [ "$PAM_TYPE" != "close_session" ]; then
        whistleblowerctl send-message --text="L'utilistateur ${PAM_USER} vient de se connecter en SSH. "
      fi
    dest: "/etc/ssh/pam-whistleblower.sh"
    mode: a+x
- name: add script for whistleblower in pam config
  blockinfile:
    block: |
      auth optional pam_exec.so seteuid /etc/ssh/pam-whistleblower.sh
      session optional pam_exec.so seteuid /etc/ssh/pam-whistleblower.sh
    state: present
    path: "/etc/pam.d/sshd"
