---
- name: delete old build folder
  file:
    path: "{{ system_maintenance_build_folder_path }}"
    state: absent
  changed_when: false

- name: create build folder
  file:
    path: "{{ system_maintenance_build_folder_path }}"
    state: absent
  changed_when: false

- name: clone git repository
  git:
    repo: "{{ system_maintenance_git_repo_url }}"
    dest: "{{ system_maintenance_build_folder_path }}"

- name: make package
  command: make build
    chdir: "{{ system_maintenance_source_folder_path }}"
