---
- name: create config folder
  file:
    path: "/etc/system-maintenance"
    state: directory
    owner: "system-maintenance"

- name: copy vault password
  copy:
    content: |
      {{ system_maintenance_vault_password }}
    dest: "/etc/system-maintenance/vault-password"
    owner: "system-maintenance"
    mode: "u=rw,g=r,o="

- name: start provision timer
  systemd:
    name: "system-maintenance@provision.timer"
    state: started
    enabled: yes

- name: start upgrade timer
  systemd:
    name: "system-maintenance@upgrade.timer"
    state: started
    enabled: yes
