---
- name: install packages
  yay:
    name: "avahi"
    state: present

- name: start service
  systemd:
    name: "avahi-daemon.service"
    state: started
    enabled: yes

- name: force IPv4
  lineinfile:
    dest: "/etc/avahi/avahi-daemon.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
  - { regexp: "(# *)?use-ipv4=.*$", line: "use-ipv4=yes" }
  - { regexp: "(# *)?use-ipv6=.*$", line: "use-ipv6=no" }
  notify: reload avahi service
