---
- name: create jail file for fail2ban
  copy:
    content: |
      [sshd]
      enabled  = true
      filter   = sshd
      action = whistleblower
               iptables[port={{ ssh_server_port }}]
      backend  = systemd
      findtime = 10m
      bantime  = 1m
      maxretry = 5
      ignoreip = 127.0.0.1/8
    dest: "/etc/fail2ban/jail.d/sshd.local"
  when: "ssh_fail2ban_state == 'present'"
  notify:
  - restart fail2ban service

- name: delete jail file for fail2ban
  file:
    path: "/etc/fail2ban/jail.d/sshd.local"
    state: absent
  when: "ssh_fail2ban_state == 'absent'"
  notify:
  - restart fail2ban service
