#!/usr/bin/env python

from whistleblower.server import Server
from whistleblower.dbus import Interface
from whistleblower.context import Context

from pydbus import SystemBus
from pydbus.generic import signal

from gi.repository import GLib


context = Context()
bus = SystemBus()
server = Server(context)
interface = Interface(server)

server.on_message_received(lambda text: interface.MessageReceived(text))

bus.publish(Interface.SERVICE_NAME, interface)
server.start()
loop = GLib.MainLoop()
try:
    loop.run()
except KeyboardInterrupt:
    loop.quit()
